<%@ Page Title="" Language="C#" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="Animal_WebApp.About" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 class="text-center">About</h2>
    <p class="contentBox">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et risus et neque suscipit sagittis ac a enim. Morbi rutrum volutpat bibendum. Nam eu tortor malesuada, cursus neque nec, sagittis tortor. Pellentesque cursus turpis vel malesuada mollis. Etiam vestibulum augue dui, vitae vehicula purus rutrum ac. In hac habitasse platea dictumst. Sed egestas lorem vel tincidunt viverra. Phasellus faucibus volutpat justo, sit amet volutpat lectus consectetur tempor. Duis at tellus sed diam porta suscipit. Morbi laoreet convallis magna eu dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec efficitur tincidunt tristique. Aliquam nec purus rutrum, lacinia odio nec, luctus tortor. Vestibulum a condimentum ex.
        <br/><br/>
Nullam hendrerit nibh diam, sed laoreet justo mattis ut. Vivamus eleifend pulvinar mauris, in elementum justo mattis ut. Quisque eleifend dictum magna. Mauris quis ante nec est mattis congue. Fusce non risus nec eros elementum tristique placerat a lectus. Quisque posuere faucibus nisi, in maximus sapien sagittis eleifend. Duis rhoncus tellus quis justo euismod imperdiet. Cras lobortis purus a ante convallis, a ullamcorper velit ornare. Nulla tincidunt ornare risus, non facilisis augue gravida nec. Praesent porta sem at libero posuere, ut consequat purus tristique. Cras lectus quam, lobortis quis nisi maximus, congue cursus mauris. Vivamus sed condimentum nulla. Mauris eleifend dui velit, sed mollis nibh bibendum ac. Phasellus sit amet faucibus erat. Etiam tincidunt dolor vel pretium fringilla.
        <br/><br/>
Cras tortor odio, tempor nec ex vel, pellentesque ultrices tortor. Ut et orci viverra, aliquam lorem et, ultricies lacus. Sed velit ex, consectetur ut ornare vitae, pretium sit amet velit. Proin fermentum, lacus quis vestibulum posuere, erat orci scelerisque erat, nec laoreet odio arcu sed arcu. Nulla facilisi. Maecenas rhoncus rutrum nisi et lobortis. Fusce vitae odio eget est maximus blandit. Sed aliquet faucibus nunc nec rutrum. Donec laoreet sem vel malesuada dictum. Etiam facilisis eget diam sed pharetra. Integer malesuada et nulla condimentum sodales. Quisque vehicula sit amet nulla non consequat. Morbi iaculis suscipit felis quis tincidunt. Quisque at nisi ipsum.
        <br/><br/>
Vestibulum vulputate ac nunc ut pretium. Vestibulum est leo, lacinia eu tempus et, pulvinar non ex. Proin a mi viverra, facilisis ligula id, auctor lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed orci dui, porta ut vestibulum sit amet, faucibus in arcu. Praesent vulputate risus eu leo viverra rhoncus. Integer quis dui non massa feugiat porttitor ac vitae ex. Phasellus dictum euismod dignissim. Suspendisse potenti. Nam posuere odio eu scelerisque convallis. Morbi convallis magna a molestie egestas. Fusce nec lobortis lorem, non mattis tortor. Phasellus interdum ut lacus eu consectetur. Vivamus commodo, turpis consequat pharetra faucibus, ipsum mauris hendrerit est, et tincidunt lectus erat non magna. Nunc pharetra, orci a tincidunt fermentum, nunc enim tincidunt lacus, at ullamcorper dui nulla sed odio. Aenean purus elit, ornare non justo id, hendrerit efficitur massa.
        <br/><br/>
Morbi ullamcorper tempus interdum. Donec volutpat semper elit, finibus feugiat augue consequat nec. Pellentesque tincidunt volutpat massa nec blandit. Proin non est tristique, semper eros et, scelerisque sem. Ut rhoncus neque molestie lorem vehicula, id venenatis leo aliquet. Aliquam molestie tincidunt augue, eu commodo libero commodo et. Proin interdum, risus ut dapibus luctus, eros massa gravida mi, nec bibendum justo leo a est. Donec eu diam ligula. Donec vestibulum pharetra eros in posuere. Morbi varius arcu nec semper iaculis.
    </p>
</asp:Content>
